BIN_NAME=fbchaind
FBCHAIN_TOP=${GOPATH}/src/github.com/FiboChain/fbc
FBCHAIN_BIN=${FBCHAIN_TOP}/build
FBCHAIN_BIN=${GOPATH}/bin
FBCHAIN_NET_TOP=`pwd`
FBCHAIN_NET_CACHE=${FBCHAIN_NET_TOP}/cache
CHAIN_ID="fbchain-3201"


BASE_PORT_PREFIX=26600
P2P_PORT_SUFFIX=56
RPC_PORT_SUFFIX=57
REST_PORT=8545
let BASE_PORT=${BASE_PORT_PREFIX}+${P2P_PORT_SUFFIX}
let seedp2pport=${BASE_PORT_PREFIX}+${P2P_PORT_SUFFIX}
let seedrpcport=${BASE_PORT_PREFIX}+${RPC_PORT_SUFFIX}
let seedrestport=${seedrpcport}+1
