BIN_NAME=fbchaind
FIBOCHAIN_TOP=${GOPATH}/src/github.com/FiboChain/fbc
FIBOCHAIN_BIN=${FIBOCHAIN_TOP}/build
FIBOCHAIN_BIN=${GOPATH}/bin
FIBOCHAIN_NET_TOP=`pwd`
FIBOCHAIN_NET_CACHE=${FIBOCHAIN_NET_TOP}/cache
CHAIN_ID="fbc-67"


BASE_PORT_PREFIX=26600
P2P_PORT_SUFFIX=56
RPC_PORT_SUFFIX=57
REST_PORT=8545
let BASE_PORT=${BASE_PORT_PREFIX}+${P2P_PORT_SUFFIX}
let seedp2pport=${BASE_PORT_PREFIX}+${P2P_PORT_SUFFIX}
let seedrpcport=${BASE_PORT_PREFIX}+${RPC_PORT_SUFFIX}
let seedrestport=${seedrpcport}+1
